version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: rag_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rag_test_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    command: sh -c "python main.py --setup && python main.py"

volumes:
  postgres_data: 